version: '3'

services:
  #openldap-shell-dev:
  #  image: openldap-shell:latest
  #  build: ./openldap
  #  container_name: openldap-shell-dev
  #  ports:
  #    - 1389:1389
  #  volumes:
  #    - ./openldap/data_dev:/data
  #    - ./openldap/command:/command
  #  command: bash -c "/data/start.sh"

  #phpldapadmin-dev:
  #  image: osixia/phpldapadmin:latest
  #  container_name: phpldapadmin-dev
  #  depends_on:
  #    - openldap-shell-dev
  #  ports:
  #    - 6443:443
  #  environment:
  #    - 'PHPLDAPADMIN_LDAP_HOSTS=#PYTHON2BASH:[{"openldap-shell-dev": [{"server": [{"port": 1389}]}]}]'

  # org0
  openldap-shell-org0:
    image: openldap-shell:latest
    build: ./openldap
    container_name: openldap-shell-org0
    ports:
      - 2389:2389
    volumes:
      - ./openldap/data_org0:/data
      - ./openldap/command:/command
    command: bash -c "/data/start.sh"

  phpldapadmin-org0:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin-org0
    ports:
      - 7443:443
    environment:
      - 'PHPLDAPADMIN_LDAP_HOSTS=#PYTHON2BASH:[{"openldap-shell-org0": [{"server": [{"port": 2389}]}]}]'

  # org1
  openldap-shell-org1:
    image: openldap-shell:latest
    build: ./openldap
    container_name: openldap-shell-org1
    ports:
      - 3389:3389
    volumes:
      - ./openldap/data_org1:/data
      - ./openldap/command:/command
    command: bash -c "/data/start.sh"

  phpldapadmin-org1:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin-org1
    depends_on:
      - openldap-shell-org1
    ports:
      - 8443:443
    environment:
      - 'PHPLDAPADMIN_LDAP_HOSTS=#PYTHON2BASH:[{"openldap-shell-org1": [{"server": [{"port": 3389}]}]}]'

  # person
  openldap-shell-person:
    image: openldap-shell:latest
    build: ./openldap
    container_name: openldap-shell-person
    ports:
      - 4389:4389
    volumes:
      - ./openldap/data_person:/data
      - ./openldap/command:/command
    command: bash -c "/data/start.sh"

  phpldapadmin-person:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin-person
    depends_on:
      - openldap-shell-org1
    ports:
      - 9443:443
    environment:
      - 'PHPLDAPADMIN_LDAP_HOSTS=#PYTHON2BASH:[{"openldap-shell-person": [{"server": [{"port": 4389}]}]}]'

  # Apps
  sshd-shell:
    image: sshd-shell:latest
    build: ./sshd
    container_name: sshd-shell
    depends_on:
      - openldap-shell-person
    ports:
      - 8022:222
    volumes:
      - ./sshd/configs:/configs_tmp
    command: bash -c "/usr/sbin/sshd & /usr/sbin/sssd & while :; do sleep 10; done"

  apache2-shell:
    image: apache2-shell:latest
    build: ./apache2
    container_name: apache2-shell
    depends_on:
      - openldap-shell-person
    ports:
      - 8081:80

  flow-emulator:
    image: flow-emulator:latest
    build: ./flow-emulator
    container_name: flow-emulator
    ports:
      - 8080:8080
      - 3569:3569
    volumes:
      - ./flow-emulator/configs:/configs
      - ../cadence/:/cadence
    command: bash -c "flow run -f /configs/flow.json"
